/*
 *  
 *   File          :   SpectrumPanel.java
 *  
 *   Project       :   atkpanel generic java application
 *  
 *   Description   :   The panel to display a  number spectrum attribute
 *  
 *   Author        :   Faranguiss Poncet
 *  
 *   Original      :   Mars 2002
 *  
 *   $Revision$				$Author$
 *   $Date$					$State$
 *  
 *   $Log$
 *  
 *   Copyright (c) 2002 by European Synchrotron Radiation Facility,
 *  		       Grenoble, France
 *  
 *                         All Rights Reserved
 *  
 *  
 */
 
package atkpanel;

/**
 *
 * @author  poncet
 */
import java.util.*;
import java.lang.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;
import fr.esrf.tangoatk.core.*;
import fr.esrf.tangoatk.widget.attribute.*;

public class SpectrumPanel extends javax.swing.JPanel {

    /** Creates new form SpectrumPanel */
    public SpectrumPanel() {
        initComponents();
    }

    /** Creates new form SpectrumPanel to display a NumberSpectrum attribute */
    public SpectrumPanel(INumberSpectrum  nsAtt)
    {
        initComponents();
        numberSpectrumJChartAdapter1.setViewer(simpleChart1);
        numberImageJTableAdapter1.setViewer(jTable1);
        numberSpectrumJChartAdapter1.setModel(nsAtt);
        numberImageJTableAdapter1.setModel(nsAtt);
        jTable1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            numberSpectrumJChartAdapter1 = new fr.esrf.tangoatk.widget.attribute.NumberSpectrumJChartAdapter();
            numberImageJTableAdapter1 = new fr.esrf.tangoatk.widget.attribute.NumberImageJTableAdapter();
            jScrollPane1 = new javax.swing.JScrollPane();
            jPanel1 = new javax.swing.JPanel();
            simpleChart1 = new com.klg.jclass.chart.beans.SimpleChart();
            jTable1 = new javax.swing.JTable();
            jCheckBox1 = new javax.swing.JCheckBox();
            
            
            setLayout(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints gridBagConstraints1;
            
            jPanel1.setLayout(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints gridBagConstraints2;
            
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints2.insets = new java.awt.Insets(3, 3, 3, 3);
            gridBagConstraints2.weightx = 1.0;
            gridBagConstraints2.weighty = 1.0;
            jPanel1.add(simpleChart1, gridBagConstraints2);
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
            ) {
                Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
                };
                
                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 1;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints2.insets = new java.awt.Insets(3, 3, 3, 3);
            gridBagConstraints2.weightx = 1.0;
            gridBagConstraints2.weighty = 1.0;
            jPanel1.add(jTable1, gridBagConstraints2);
            
            jScrollPane1.setViewportView(jPanel1);
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(3, 3, 3, 5);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints1);
        
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("View Graph");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGraphActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jCheckBox1, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void viewGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGraphActionPerformed
        // Add your handling code here:
	if (jCheckBox1.isSelected())
	{
	   jTable1.setVisible(false);
	   simpleChart1.setVisible(true);
	}
	else
	{
	   jTable1.setVisible(true);
	   simpleChart1.setVisible(false);
	}
    }//GEN-LAST:event_viewGraphActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.esrf.tangoatk.widget.attribute.NumberSpectrumJChartAdapter numberSpectrumJChartAdapter1;
    private fr.esrf.tangoatk.widget.attribute.NumberImageJTableAdapter numberImageJTableAdapter1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel1;
    private com.klg.jclass.chart.beans.SimpleChart simpleChart1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables

}
